### ISSUE TITLE
Crashes on Android 13 (latest build)

### ISSUE THREAD

**Issue by 4vanyek** [skyline-emu/skyline#2048]
Crash log:
`time: 1670239550594
msg: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{skyline.emu/emu.skyline.MainActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2169)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1813)
	at android.app.Activity.startActivityForResult(Activity.java:5470)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(ActivityCompat.java:766)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:241)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:237)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:175)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at emu.skyline.MainActivity.setupAppList(MainActivity.kt:215)
	at emu.skyline.MainActivity.onCreate(MainActivity.kt:122)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8269)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1392)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
	... 12 more`

**Comment by iniMerchant64** [comment]
Your android rom has some issue with permisions or the default android file selector is disabled. Log clearly says its failing to open the file explorer/selector

**Comment by Swizzlefowl** [comment]
Are you using a custom ROM? or stock.

**Comment by 4vanyek** [comment]
> Log clearly says its failing to open the file explorer/selector

Oh, I noticed that I'm missing DocumentsUI

**Comment by JERD001** [comment]
Either Cherish OS source is broken or the device tree is broken, either way is better to go for another rom and from another dev if possible.
