### ISSUE TITLE
Unable open GPU Driver Configuration

### ISSUE THREAD

**Issue by bluespada** [skyline-emu/skyline#2068]
When i need to change driver configuration the driver configuration screen always closing automaticaly

and here is some logs

```
12-10 21:19:23.868  2097  2148 W WindowManager: Failed to deliver inset state change to w=Window{4d0c040 u0 skyline.emu/emu.skyline.SettingsActivity EXITING}
12-10 21:19:23.868  2097  2148 W WindowManager: android.os.DeadObjectException
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3994)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$5$com-android-server-wm-InsetsStateController(InsetsStateController.java:348)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda4.run(Unknown Source:2)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:840)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:784)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowManagerService.postWindowRemoveCleanupLocked(WindowManagerService.java:2090)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowState.removeImmediately(WindowState.java:2492)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowState.removeIfPossible(WindowState.java:2640)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowState.removeIfPossible(WindowState.java:2498)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2031)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:223)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:5199)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:8474)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.view.ViewRootImpl.die(ViewRootImpl.java:8450)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:500)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:441)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:206)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.app.Dialog.dismissDialog(Dialog.java:404)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.app.Dialog.dismiss(Dialog.java:386)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.am.AppErrorDialog.dismiss(AppErrorDialog.java:163)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda4.accept(Unknown Source:2)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.am.ErrorDialogController.forAllDialogs(ErrorDialogController.java:164)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.am.ErrorDialogController.lambda$scheduleForAllDialogs$0$com-android-server-am-ErrorDialogController(ErrorDialogController.java:157)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.am.ErrorDialogController$$ExternalSyntheticLambda5.run(Unknown Source:6)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-10 21:19:23.868  2097  2148 W WindowManager: 	at com.android.server.UiThread.run(UiThread.java:45)
12-10 21:19:23.869  2097 12996 D CoreBackPreview: Window{766af42 u0 Splash Screen skyline.emu}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@30d6cf2, mPriority=0}
12-10 21:19:23.872  2097  2151 W WindowManager: Failed to deliver inset state change to w=Window{4d0c040 u0 skyline.emu/emu.skyline.SettingsActivity EXITING}
12-10 21:19:23.872  2097  2151 W WindowManager: android.os.DeadObjectException
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.view.IWindow$Stub$Proxy.insetsControlChanged(IWindow.java:473)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.wm.WindowState.notifyInsetsControlChanged(WindowState.java:3994)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.wm.InsetsStateController.lambda$notifyPendingInsetsControlChanged$5$com-android-server-wm-InsetsStateController(InsetsStateController.java:348)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.wm.InsetsStateController$$ExternalSyntheticLambda4.run(Unknown Source:2)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.wm.WindowAnimator.executeAfterPrepareSurfacesRunnables(WindowAnimator.java:345)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.wm.WindowAnimator.animate(WindowAnimator.java:226)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.wm.WindowAnimator.lambda$new$1$com-android-server-wm-WindowAnimator(WindowAnimator.java:106)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.wm.WindowAnimator$$ExternalSyntheticLambda1.doFrame(Unknown Source:2)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.view.Choreographer.doFrame(Choreographer.java:827)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-10 21:19:23.872  2097  2151 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-10 21:19:23.884 14685 14691 I adbd    : jdwp connection from 5387
12-10 21:19:23.885  2921  3060 W Parcel  : Expecting binder but got null!
12-10 21:19:23.893  2097 12996 I AppsFilter: interaction: PackageSetting{499dc01 skyline.emu/10315} -> PackageSetting{c070179 com.google.android.apps.nexuslauncher/10225} BLOCKED
12-10 21:19:23.895  2097  2151 W WindowManager: Exception thrown during dispatchAppVisibility Window{4d0c040 u0 skyline.emu/emu.skyline.SettingsActivity EXITING}
12-10 21:19:23.895  2097  2151 W WindowManager: android.os.DeadObjectException
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.os.BinderProxy.transactNative(Native Method)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.view.IWindow$Stub$Proxy.dispatchAppVisibility(IWindow.java:536)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.WindowState.sendAppVisibilityToClients(WindowState.java:3489)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.WindowContainer.sendAppVisibilityToClients(WindowContainer.java:1199)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.WindowToken.setClientVisible(WindowToken.java:398)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.ActivityRecord.setClientVisible(ActivityRecord.java:6568)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.ActivityRecord.onAnimationFinished(ActivityRecord.java:7355)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.ActivityRecord.postApplyAnimation(ActivityRecord.java:5267)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5239)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.ActivityRecord.commitVisibility(ActivityRecord.java:5243)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleClosingApps(AppTransitionController.java:1098)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.AppTransitionController.handleAppTransitionReady(AppTransitionController.java:286)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.RootWindowContainer.checkAppTransitionReady(RootWindowContainer.java:975)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacementNoTrace(RootWindowContainer.java:842)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.RootWindowContainer.performSurfacePlacement(RootWindowContainer.java:784)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop(WindowSurfacePlacer.java:177)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:126)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement(WindowSurfacePlacer.java:115)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.wm.WindowSurfacePlacer$Traverser.run(WindowSurfacePlacer.java:57)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.os.Handler.handleCallback(Handler.java:942)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.os.Looper.loopOnce(Looper.java:201)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.os.Looper.loop(Looper.java:288)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
12-10 21:19:23.895  2097  2151 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:44)
12-10 21:19:23.895  5387  5387 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10315; state: ENABLED
```

Device : Pocophone F3
OS : Project Zephyrus A13 (Custom Rom)

**Comment by Swizzlefowl** [comment]
It might be because of your Custom ROM.

**Comment by AbandonedCart** [comment]
> > It might be because of your Custom ROM.
> 
> I thnik is compability issue with A12+ reference by this issue #2048

The issue you referenced is part of the SAF (Storage Access Framework) revision that forced apps to use different file management endpoints. The logs you posted point to a failure in the WindowManager, which is part of the frameworks.

**Comment by Septiep** [comment]
please, I can't install the driver because it doesn't support it, how do I make it support? My gpu is mali g57, my device is poco m4

**Comment by JERD001** [comment]
Buy another phone but this time with snapdragon.

**Comment by bluespada** [comment]
> > > It might be because of your Custom ROM.
> > 
> > I thnik is compability issue with A12+ reference by this issue #2048
> 
> The issue you referenced is part of the SAF (Storage Access Framework) revision that forced apps to use different file management endpoints. The logs you posted point to a failure in the WindowManager, which is part of the frameworks.
> 
> https://stackoverflow.com/a/69462182/461982 claims that https://github.com/skyline-emu/skyline/blob/262ee28611289848e7f1d8fdbab5333eb79924d1/app/src/main/java/emu/skyline/SettingsActivity.kt#L35 prevents https://github.com/skyline-emu/skyline/blob/262ee28611289848e7f1d8fdbab5333eb79924d1/app/src/main/java/emu/skyline/SettingsActivity.kt#L86-L90 from working, but the result should be that the padding is never updated because the listener is never triggered.

Any planning to fixing this issue ?

**Comment by AbandonedCart** [comment]
> which is part of the [frameworks](https://android.googlesource.com/platform/frameworks/base/)

Even if it wasn't the root cause, it was evidence of a faulty ROM. I didn't need to be convinced of that.
